// guest
export const GET_HOT_POSTS_SUCCESS = 'GET_HOT_POSTS_SUCCESS';
export const GET_NEW_POSTS_SUCCESS = 'GET_NEW_POSTS_SUCCESS';
export const GET_CONTROVERSIAL_POSTS_SUCCESS =
  'GET_CONTROVERSIAL_POSTS_SUCCESS';
export const GET_TOP_POSTS_SUCCESS = 'GET_TOP_POSTS_SUCCESS';

// user has logged in
export const GET_HOT_POSTS_IN_FEED_SUCCESS = 'GET_HOT_POSTS_IN_FEED_SUCCESS';
export const GET_NEW_POSTS_IN_FEED_SUCCESS = 'GET_NEW_POSTS_IN_FEED_SUCCESS';
export const GET_CONTROVERSIAL_POSTS_IN_FEED_SUCCESS =
  'GET_CONTROVERSIAL_POSTS_IN_FEED_SUCCESS';
export const GET_TOP_POSTS_IN_FEED_SUCCESS = 'GET_TOP_POSTS_IN_FEED_SUCCESS';

export const SET_POST_LOADING = 'SET_POST_LOADING';
